# Generated by Django 4.0.3 on 2022-04-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=35)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=6)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='app.department')),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='app.project')),
            ],
        ),
    ]
